---
title: Pilot data for CaLLab implementation of manybabies1 
author: Dan Yurovsky 
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: hide
---

```{r setup, include = FALSE}
# load packages
library(knitr)
library(tidyverse)
library(rhdf5)
library(stringr)
library(DT)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)

theme_dy <- function(base_size = 14) 
{
  theme_bw() +   
  ggplot2::`%+replace%`(ggplot2::theme_bw(base_size = base_size),
                          ggplot2::theme(panel.grid = ggplot2::element_blank(), 
        legend.position = "none"))
}

theme_set(theme_dy())
```

```{r}
files <- paste("data/", list.files("data/", "*.hdf5"), sep = "")

read_data <- function(file) {
  
  data <- h5read(file, "data_collection/events/eyetracker/BinocularEyeSampleEvent") %>%
    as_data_frame()
  
  events <- h5read(file, "data_collection/events/experiment/MessageEvent") %>%
    as.data.frame() %>%
    select(time, text) %>%
    separate(text, c("stimulus", "type"), "_") %>%
    group_by(stimulus, type) %>%
    mutate(trial = 1:n()) %>%
    as.data.frame()
  
  filter_data <- data %>%
    select(time, status,left_gaze_x, left_gaze_y, left_eye_cam_x, 
           left_eye_cam_y,
           right_gaze_x, right_gaze_y, right_eye_cam_x, 
          right_eye_cam_y)
  
  tag_data <- function(rows) {
    filter_data %>%
      filter(time >= rows[1,"time"] & time < rows[2,"time"]) %>%
      mutate(stimulus = rows[1,"stimulus"], 
             trial = rows[1,"trial"])
  }
  
  lapply(seq(1,nrow(events),2), 
         function(x) tag_data(events[x:(x+1),])) %>%
    bind_rows() %>%
    mutate(right_gaze_x = if_else(status == 2 | status == 22, 
                                  as.numeric(NA), right_gaze_x),
           right_gaze_y = if_else(status == 2 | status == 22, 
                                  as.numeric(NA), right_gaze_y),
           left_gaze_x = if_else(status == 20 | status == 22, 
                                 as.numeric(NA), left_gaze_x),
           left_gaze_y = if_else(status == 20 | status == 22, 
                                 as.numeric(NA), left_gaze_y)) %>%
    group_by(stimulus, trial) %>%
    mutate(time = time - min(time)) %>%
    mutate(subj = str_split(file, "/")[[1]][2])
}

gaze_data <- map(files, read_data) %>%
  bind_rows()

durations <- gaze_data %>%
  group_by(subj,stimulus, trial) %>%
  summarise(duration = max(time))

datatable(durations, rownames = FALSE)
```

```{r plots, fig.width = 5, fig.height = 12}
make_plots <- function(gaze_data) {
  
  print(paste0("Subj: ", gaze_data[1,"subj"]))
  
  p1 <- ggplot(gaze_data, aes(x = time)) +
    facet_grid(trial ~ stimulus, scales = "free") +
    geom_point(aes(y = left_gaze_x), color = "red", size = .1, alpha = .5) +
    geom_point(aes(y = right_gaze_x), color = "blue", size = .1, alpha = .5) +
    ylab("X Points")
  print(p1)
  
  p2 <- ggplot(gaze_data, aes(x = time)) +
    facet_grid(trial ~ stimulus, scales = "free") +
    geom_point(aes(y = left_gaze_y), color = "red", size = .1, alpha = .5) +
    geom_point(aes(y = right_gaze_y), color = "blue", size = .1, alpha = .5) +
    ylab("Y Points")
  print(p2)
}

gaze_data %>%
  split(.$subj) %>%
  walk(., make_plots)
```