---
title: Pilot data for CaLLab implementation of manybabies1 
author: Dan Yurovsky 
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: hide
---

```{r setup, include = FALSE}
# load packages
library(knitr)
library(data.table)
library(tidyverse)
#http://bioconductor.org/packages/release/bioc/html/rhdf5.html
library(rhdf5)
library(stringr)
library(here)
library(DT)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = FALSE, tidy = FALSE)

theme_dy <- function(base_size = 14) 
{
  theme_bw() +   
  ggplot2::`%+replace%`(ggplot2::theme_bw(base_size = base_size),
                          ggplot2::theme(panel.grid = ggplot2::element_blank(), 
        legend.position = "none"))
}

theme_set(theme_dy())
```

```{r data-files}
et_files_younger <- list.files(here("data/younger"), "*.hdf5", 
                               full.names = TRUE)
log_files_younger <- list.files(here("data/younger"), "*.log", 
                                full.names = TRUE)
trial_files_younger <- list.files(here("data/younger"), "*.csv", 
                                  full.names = TRUE)


et_files_older <- list.files(here("data/older"), "*.hdf5", 
                             full.names = TRUE)

log_files_older <- list.files(here("data/older"), "*.log", 
                                full.names = TRUE)

trial_files_older <- list.files(here("data/older"), "*.csv", 
                                  full.names = TRUE) 
```

```{r loading-helpers}
get_end_times <- function(log_file) {
 end_times <- data_frame(text = read_lines(log_file)) %>%
    filter(str_detect(text, "autoDraw = False")) %>%
    filter(str_detect(text, "checkerboard") | str_detect(text, "attention_getter")) %>%
    separate(text, c("End", "EXP", "message"), sep = "\t") %>%
    mutate(type = if_else(str_detect(message, "attention_getter"), 
                          "Attention", "Trial")) %>%
    select(End, type) 
 
 if(nrow(end_times) > 0)
  end_times %>%
     mutate(trial = rep(1:(n()/2), each = 2),
            End = as.numeric(End))
 else
   end_times
}

get_trial_data <- function(trial_file) {
  read_csv(trial_file) %>%
    select(Stimulus, trials.thisTrialN, attention_key.keys, trial_key.keys) %>%
    rename(trial = trials.thisTrialN, 
           Attention = attention_key.keys, 
           Trial = trial_key.keys) %>%
    mutate(trial = trial + 1) %>%
    gather(type, key, Attention, Trial) %>%
    mutate(speechType = if_else(str_detect(Stimulus, "training"), "training",
                                if_else(str_detect(Stimulus, "ADS"), "ADS", "IDS"))) %>%
    mutate(stimNum = as.numeric(if_else(str_detect(Stimulus, "training"),
                                        as.character(trial),
                                        str_extract(Stimulus, "[0-9]+"))))
      
}

get_event_data <- function(et_file) {
  
  h5read(et_file, "data_collection/events/experiment/MessageEvent") %>%
    as_data_frame() %>%
    select(time, text) %>%
    separate(text, c("stimulus", "type"), "_") %>%
    rename(type = stimulus, event = type) %>%
    mutate(trial = rleid(type)) %>%
    distinct(event, type, trial, .keep_all = T) %>%
    spread(event, time) %>%
    group_by(type) %>%
    mutate(trial = 1:n())
}

# 
# order_data <- read_csv("order1.csv") %>%
#   mutate(trial = 1:nrow(.)) %>%
#   rename(item = Stimulus) %>%
#   mutate(type = if_else(item == "training", "training", 
#                         if_else(str_detect(item, "IDS"), "IDS", "ADS")))

read_data <- function(et_file, trial_file, log_file) {
  
  print(et_file)
  
  end_times <- get_end_times(log_file)
  trial_data <- get_trial_data(trial_file)
  event_data <- get_event_data(et_file)
  
  if(nrow(end_times) > 0) {
    order_data <- filter(event_data, is.na(End)) %>%
        select(-End) %>%
        left_join(end_times, by = c("type", "trial")) %>%
        bind_rows(filter(event_data, !is.na(End))) %>%
        left_join(trial_data, by = c("type", "trial")) %>%
        arrange(trial, type)
  } else {
     order_data <- event_data %>%
        left_join(trial_data, by = c("type", "trial")) %>%
        arrange(trial, type)
  }
  
  data <- h5read(et_file, "data_collection/events/eyetracker/BinocularEyeSampleEvent") %>%
    as_data_frame()
  
  filter_data <- data %>%
    select(time, status,left_gaze_x, left_gaze_y, left_eye_cam_x, 
           left_eye_cam_y,
           right_gaze_x, right_gaze_y, right_eye_cam_x, 
          right_eye_cam_y)
  
  
  tag_data <- function(row) {
    filter_data %>%
      filter(time >= row$Start & time < row$End) %>%
      mutate(type = row$type, 
             trial = row$trial)
  }
  
  
  map(seq(1,nrow(order_data)), 
         function(x) tag_data(order_data[x,])) %>%
    bind_rows() %>%
    mutate(right_gaze_x = if_else(status == 2 | status == 22,
                                  as.numeric(NA), right_gaze_x),
           right_gaze_y = if_else(status == 2 | status == 22,
                                  as.numeric(NA), right_gaze_y),
           left_gaze_x = if_else(status == 20 | status == 22,
                                 as.numeric(NA), left_gaze_x),
           left_gaze_y = if_else(status == 20 | status == 22,
                                 as.numeric(NA), left_gaze_y)) %>%
    group_by(trial, type) %>%
    mutate(time = time - min(time)) %>%
    mutate(subj = str_split(et_file, "/")[[1]][3]) %>%
    left_join(order_data, by = c("type", "trial"))
}
```

```{r load-data, message = F, warning = FALSE}
gaze_data_younger <- pmap(list(et_files_younger, trial_files_younger, 
                               log_files_younger), read_data) %>%
  bind_rows() %>%
  mutate(group = "younger")

gaze_data_older <- pmap(list(et_files_older, trial_files_older, 
                               log_files_older), read_data) %>%
  bind_rows() %>%
  mutate(group = "older")


gaze_data <- bind_rows(gaze_data_younger, gaze_data_older)

write_csv(gaze_data, here("processed_data/callab_manybabies_et.csv"))
```

```{r process-data, eval = F, include = F}
durations <- gaze_data %>%
  group_by(subj, type, speechType, trial) %>%
  summarise(duration = max(time))

datatable(durations, rownames = FALSE)

sem <- function (x, na.rm = FALSE) 
{
    if (na.rm) {
        n <- sum(!is.na(x))
    }
    else {
        n <- length(x)
    }
    stats::sd(x, na.rm = na.rm)/sqrt(n)
}

subjs <- gaze_data %>%
  ungroup() %>%
  distinct(subj) %>%
  rowwise() %>%
  mutate(subid = str_split(subj, "_", simplify = T)[1]) %>%
  ungroup() %>%
  mutate(subid = paste0("callab_", subid)) %>%
  mutate(lab = "callab")

mb_data <- gaze_data %>%
  filter(type == "Trial") %>%
  group_by(subj, speechType, trial, stimNum) %>%
  arrange(time) %>%
  mutate(diff_time = time - lag(time),
         looking_time = diff_time * (status != 22)) %>%
  summarise(total_trial_time = sum(diff_time, na.rm = T), 
            looking_time = sum(looking_time, na.rm = T)) %>%
  left_join(subjs) %>%
  ungroup() %>%
  mutate(stimulus = if_else(speechType == "training", "training",
                            paste0(speechType, stimNum)),
         trial_num = if_else(stimulus == "training", trial-3, trial -2),
         trial_error = "noerror",
         trial_error_type = NA,
         notes = NA) %>%
  rename(trial_type = speechType) %>%
  select(lab, subid, trial_type, stimulus, trial_num, looking_time, total_trial_time,
         trial_error, trial_error_type, notes) %>%
  arrange(subid, trial_num)

write_csv(mb_data, "callab_older.csv")

mb_data %>%
  filter(looking_time > 0) %>%
  group_by(trial_type, subid) %>%
  summarise(looking_time = mean(looking_time)) %>%
  summarise(mean = mean(looking_time), sem = sem(looking_time))

mb_data %>%
  bind_rows(read_csv("callab_younger.csv")) %>%
  write_csv("callab_manybabies.csv")

subjs %>%
  rowwise() %>%
  mutate(subj = str_split(subj, "[_.]", simplify = T)[4:6] %>% paste0(collapse = "_")) %>%
  select(-lab) %>%
  mutate(group = "younger") %>%
  bind_rows(read_csv("older_subjs.csv")) %>%
  write_csv("subjs.csv")


```

```{r plots, fig.width = 5, fig.height = 12, eval = F, include = F}
make_plots <- function(gaze_data) {
  
  print(paste0("Subj: ", gaze_data[1,"subj"]))
  
  p1 <- ggplot(gaze_data, aes(x = time)) +
    facet_grid(trial ~ type, scales = "free") +
    geom_point(aes(y = left_gaze_x), color = "red", size = .1, alpha = .5) +
    geom_point(aes(y = right_gaze_x), color = "blue", size = .1, alpha = .5) +
    ylab("X Points")
  print(p1)
  
  p2 <- ggplot(gaze_data, aes(x = time)) +
    facet_grid(trial ~ type, scales = "free") +
    geom_point(aes(y = left_gaze_y), color = "red", size = .1, alpha = .5) +
    geom_point(aes(y = right_gaze_y), color = "blue", size = .1, alpha = .5) +
    ylab("Y Points")
  print(p2)
}

gaze_data %>%
  filter(subj == unique(gaze_data$subj)[8]) %>%
  split(.$subj) %>%
  walk(., make_plots)
```